### ISSUE TITLE
Would be nice to have a list of default animations that people can use out of the box. 

### ISSUE THREAD

**Issue by dkwin** [hyperfuse/react-anime#1]
It would be nice to have a list of default animations that can be used out of the box.  

For example, animate.css has animations such as:
- bounce
- flash
- rubberBand
- fadeIn

etc

See the example here:  

https://daneden.github.io/animate.css/

**Comment by kennetpostigo** [comment]
@dkwin thanks for opening this issue! This project is based on the anime package and if you take a look at their default animtion [easings](https://github.com/juliangarnier/anime#parameters) where they ask you to `console.log(Object.keys(anime.easings))` you will get the following animations out of the box:
```js
[
"easeInSine", "easeOutSine", "easeInOutSine", "easeInCirc", "easeOutCirc", "easeInOutCirc", "easeInElastic", "easeOutElastic", "easeInOutElastic", "easeInBack", "easeOutBack", "easeInOutBack", "easeInBounce", "easeOutBounce", "easeInOutBounce", "easeInQuad", "easeOutQuad", "easeInOutQuad", "easeInCubic", "easeOutCubic", "easeInOutCubic", "easeInQuart", "easeOutQuart", "easeInOutQuart", "easeInQuint", "easeOutQuint", "easeInOutQuint", "easeInExpo", "easeOutExpo", "easeInOutExpo", "linear"
]
```

Is this what you were looking for?

**Comment by alaingalvan** [comment]
Some default animations is a good idea, perhaps some examples in the readme:

## Fade Down

- [Codepen Example](http://codepen.io/alaingalvan/pen/RGWbmp)

```js
<Anime opacity={[0, 1]} translateY={'1em'} delay={(e, i) => i * 100}>
  <h1>Blog Post</h1>
  <section>
    <p>Upon this, Daggoo, with either hand upon the gunwale to steady his way, swiftly slid aft, and then erecting himself volunteered his lofty shoulders for a pedestal.</p>
  <p>"Good a mast-head as any, sir. Will you mount?"</p>
  <p>"That I will, and thank ye very much, my fine fellow; only I wish you fifty feet taller."</p>
  </section>
</Anime>
```

What could work is a set of defaults like:

```js
import Anime, {presets} from 'react-anime';

export default (props) => (
  <Anime {...presets.fadeDown}>
    <p>Upon this, Daggoo, with either hand...</p>
  </Anime>
);
```

**Comment by kennetpostigo** [comment]
@alaingalvan awesome! we definitely need more examples. Also I think Im going to add and examples section to the github page.

**Comment by dkwin** [comment]
Ah, that helps!

**Comment by dkwin** [comment]
One useful example would be to use the animations when an object appears and disappears.  React's animation Group has the events to be able to animate whenever the object appears and hides.

**Comment by kennetpostigo** [comment]
@dkwin great suggestion! @alaingalvan and I will work on more documentation and examples and try to get them out ASAP!

**Comment by polmoneys** [comment]
thank you all for working on this, finally some joy out of animating in react :)

**Comment by kennetpostigo** [comment]
@polmoneys thank you for the kind words :)
