### ISSUE TITLE
Requires Animejs

### ISSUE THREAD

**Issue by Crizzooo** [hyperfuse/react-anime#19]
Hey,

I'm building a React-Anime button with an animated SVG and I want to publish it on NPM.

So that component would be a peer dependency of your project. But when I install your project, it does  not automatically install `animejs`.

Is this on purpose? Could you explain why?

Now when I publish mine, do I just require your package and leave a note for the user that they will need to `npm i -S animejs` themselves?

**Comment by alaingalvan** [comment]
That's weird, `animejs` is a dependency in the version of React Anime on NPM. 

```js
// Current React Anime package.json
{
  // ...
  "peerDependencies": {
    "react": "^15.3.1",
    "react-dom": "^15.3.1"
  },
  "dependencies": {
    "animejs": "1.1.1"
  }
}
```

Am I missing something here? Since `animejs` is a direct dependency it shouldn't be doing that. Can I see
 your package.json? 😕
