### ISSUE TITLE
Docs and examples links don't work?

### ISSUE THREAD

**Issue by hilary-L** [hyperfuse/react-anime#20]
Clicking on the link to either the API Docs or the Examples from the repo homepage just reloads the main https://hyperfuse.github.io/react-anime/ page...

**Comment by AntonVoltchok** [comment]
I looked at the code it looks like there should be some kind of navigation showing up but it doesn't, maybe something wrong with router

**Comment by alaingalvan** [comment]
Yeah, the examples are currently on Codepen, was planning on making them first class on the website though. 

Working atm, but I'll post a link to the codepen collection on the site as soon as possible and edit this post when it's up. ;)

**Comment by pencilcheck** [comment]
Still can't open documentation :(

**Comment by ssageghi** [comment]
@alaingalvan
 Hi
are documents fixed?

**Comment by skumblue** [comment]
Something for here?

**Comment by alaingalvan** [comment]
[For now there's a collection on Codepen that you all could use for examples. ;)](https://codepen.io/collection/nrkjgo/)

**Comment by tomprogers** [comment]
Still no docs. Still deal-breaker.

Looks like a great tool. Don't have the first idea how to use it.

**Comment by pencilcheck** [comment]
Still doesn't work, I don't know why this is closed.

**Comment by alaingalvan** [comment]
The collection on CodePen is now the default place to find examples. As for documentation I went ahead and added a [docs.md](https://github.com/hyperfuse/react-anime/blob/master/docs.md) file that can be found in the `readme.md` description. 

That document details all the props an `<Anime/>` component expects, as well as the TLDR on how to use it. users just pass in CSS attributes, HTML attributes, or SVG attributes. Anything they want animated. ;)
