### ISSUE TITLE
Keyframes not working?

### ISSUE THREAD

**Issue by pgsil** [hyperfuse/react-anime#21]
Not sure if this is a known issue or not, just want to make sure.
Keyframes don't seem to work.

```javascript
<Anime easing="easeInOutCirc"
	targets={".highlightcolor"}
	loop={true}
	color={["#0000FF", "#FF0000", "#00FF00"]}
	translateX={[
		{ value: 250, duration: 1000, delay: 500, elasticity: 0 },
		 { value: 0, duration: 1000, delay: 500, elasticity: 0 }
	]}>
```

Does absolutely nothing when it comes to translation. The color property is only animated between "#0000FF", "#FF0000", so that's also not how these are supposed to work here, I guess.

Am I doing something wrong?

**Comment by yunyu** [comment]
I'm wondering why this is closed, I can't seem to get this working either.
