### ISSUE TITLE
npm is out of date

### ISSUE THREAD

**Issue by ekeric13** [hyperfuse/react-anime#25]
Can you push up a new version of the package onto npm?

The local code is at version 2.0.2.
https://github.com/hyperfuse/react-anime/blob/master/packages/react-anime/package.json

But the code on npm is back at 0.3.4.
https://www.npmjs.com/package/react-anime

When I went to make a fix in the package I realized that the react lifecycle methods have since changed.

**Comment by hawkins** [comment]
I'm wondering why npm hasn't been updated in over a year, despite it being very popular and not exactly inactive in terms of development. 🤔 

@kennetpostigo @alaingalvan , do you need help maintaining / supporting this project? I'm sure a few contributors or users like myself would be happy to help out.

---

Interesting stats on the package, showing its use (1.5M dependents!)

![image](https://user-images.githubusercontent.com/9123458/31748313-e64253ea-b437-11e7-8c9c-7027c4b831f3.png)

> img from https://yarnpkg.com/en/package/react-anime

**Comment by alaingalvan** [comment]
Updated the NPM distribution to `2.0.0`. ;)

@hawkins - the project is open to pull requests, if you have a cool idea and want to contribute, feel free to send a pull request over. 😄
