### ISSUE TITLE
react-motion > react-anime

### ISSUE THREAD

**Issue by dcsan** [hyperfuse/react-anime#56]
seems like you changed the package name?
but still it refers to react-motion in the online docs.

https://alain.xyz/libraries/react-anime

![image](https://user-images.githubusercontent.com/514002/61952052-bce5f900-afaa-11e9-821c-c9a8ec25845b.png)

**Comment by tomhoad** [comment]
Motion is a different package that solves a different issue. React-anime is a wrapper around Anime.js.
