### ISSUE TITLE
Breaks immediately with Next.Js

### ISSUE THREAD

**Issue by 2manypistachios** [hyperfuse/react-anime#69]
I haven't been able to use the package at all, starting from a default Next project, using
npx create-next-app

Depending on:
  "dependencies": {
    "animejs": "^3.1.0",
    "next": "9.1.6",
    "react": "16.12.0",
    "react-anime": "^2.3.2",
    "react-dom": "16.12.0"
  }

I tried to run tests with and without animejs, both failing.

Getting errors in the browser saying:
`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: e dll_d6a88dbe3071bd165157.js:12608:15
The above error occurred in the <e> component:
    in e (at pages/index.js:6)
    in div (at pages/index.js:5)
    in Home (created by App)
    in App
    in Container (created by AppContainer)
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, App. index.js:1
The above error occurred in the <App> component:
    in App
    in Container (created by AppContainer)
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, Container. index.js:1
TypeError: y.remove is not a function
2 react-anime.js:1
Source map error: Error: Invalid URL: webpack://[name]_[chunkhash]/webpack/bootstrap
Resource URL: http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1577834418975
Source Map URL: dll_d6a88dbe3071bd165157.js.map`

The page temporarily loads and then glitches out.

**Comment by alaingalvan** [comment]
Thanks for the heads up, I'm seeing those warnings on my end when running these tests, working on a patch now. 

I'll edit this reply once it's ready. 👨‍🍳
